from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from math import floor

import httpx
from sqlalchemy.orm import Session

from app.models.models import (
    ArticlePlanningSettings,
    BundleType,
    GlobalPlanningSettings,
    PlanningSettings,
)
from app.schemas.planning_production_order import (
    ProductionOrderAlternative,
    ProductionOrderProposalFromWbRequest,
    ProductionOrderProposalRequest,
    ProductionOrderProposalResponse,
    ProductionOrderRecommendation,
    ProductionOrderRecommendationLine,
    ProductionOrderResourceAllocationApplied,
    ResourceAllocationBundleReservation,
    ResourceAllocationReservation,
)
from app.services.planning_production_order_article import (
    _build_article_not_found_detail as _extracted_build_article_not_found_detail,
    _require_article as _extracted_require_article,
)
from app.services.planning_production_order_assorti_application import (
    _AssortiApplicationResult as _extracted_AssortiApplicationResult,
    _apply_production_order_assorti_classification as _extracted_apply_production_order_assorti_classification,
)
from app.services.planning_production_order_assorti import (
    ASSORTI_CLASSIFICATION_ADMIN_FALLBACK_SOURCE as EXTRACTED_ASSORTI_CLASSIFICATION_ADMIN_FALLBACK_SOURCE,
    ASSORTI_CLASSIFICATION_GLOBAL_FALLBACK_SOURCE as EXTRACTED_ASSORTI_CLASSIFICATION_GLOBAL_FALLBACK_SOURCE,
    ASSORTI_CLASSIFICATION_MISSING_SOURCE as EXTRACTED_ASSORTI_CLASSIFICATION_MISSING_SOURCE,
    ASSORTI_CLASSIFICATION_SOURCE as EXTRACTED_ASSORTI_CLASSIFICATION_SOURCE,
    _load_assorti_bundle_type_flags,
    _parse_assorti_bundle_type_ids,
)
from app.services.planning_production_order_economics import (
    CAPITAL_CONSTRAINT_STATUS_MISSING_STRICT as EXTRACTED_CAPITAL_CONSTRAINT_STATUS_MISSING_STRICT,
    ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_ASSORTI as EXTRACTED_ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_ASSORTI,
    ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_MAIN as EXTRACTED_ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_MAIN,
    ECONOMICS_DEFAULT_LOGISTICS_COST_PER_UNIT as EXTRACTED_ECONOMICS_DEFAULT_LOGISTICS_COST_PER_UNIT,
    ECONOMICS_DEFAULT_PRODUCTION_COST_PER_UNIT as EXTRACTED_ECONOMICS_DEFAULT_PRODUCTION_COST_PER_UNIT,
    ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_ASSORTI as EXTRACTED_ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_ASSORTI,
    ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_MAIN as EXTRACTED_ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_MAIN,
    ECONOMICS_FORMULA_VERSION as EXTRACTED_ECONOMICS_FORMULA_VERSION,
    ECONOMICS_TRUST_KEY_FIELDS as EXTRACTED_ECONOMICS_TRUST_KEY_FIELDS,
    ECONOMICS_TRUST_LEVEL_PARTIAL as EXTRACTED_ECONOMICS_TRUST_LEVEL_PARTIAL,
    ECONOMICS_TRUST_LEVEL_TRUSTED as EXTRACTED_ECONOMICS_TRUST_LEVEL_TRUSTED,
    ECONOMICS_TRUST_LEVEL_UNTRUSTED as EXTRACTED_ECONOMICS_TRUST_LEVEL_UNTRUSTED,
    ECONOMICS_TRUST_UNTRUSTED_CODE_DEFAULT_THRESHOLD as EXTRACTED_ECONOMICS_TRUST_UNTRUSTED_CODE_DEFAULT_THRESHOLD,
    ECONOMICS_TRUST_WARNING_CODE_PARTIAL as EXTRACTED_ECONOMICS_TRUST_WARNING_CODE_PARTIAL,
    ECONOMICS_TRUST_WARNING_CODE_UNTRUSTED as EXTRACTED_ECONOMICS_TRUST_WARNING_CODE_UNTRUSTED,
    FROM_WB_OBSERVED_ECONOMIC_SOURCE as EXTRACTED_FROM_WB_OBSERVED_ECONOMIC_SOURCE,
    LAYER_PROXY_VALUE_SOURCE as EXTRACTED_LAYER_PROXY_VALUE_SOURCE,
    _EffectiveEconomicSettings,
    _normalize_non_negative_float,
    _resolve_economic_trust_and_capital_governance as _extracted_resolve_economic_trust_and_capital_governance,
    _resolve_economic_settings,
)
from app.services.planning_production_order_economic_governance_application import (
    _EconomicGovernanceApplicationResult as _extracted_EconomicGovernanceApplicationResult,
    _apply_production_order_economic_governance as _extracted_apply_production_order_economic_governance,
)
from app.services.planning_production_order_explainability import (
    EXPLAINABILITY_MODE_COMPACT as EXTRACTED_EXPLAINABILITY_MODE_COMPACT,
    _apply_from_wb_explainability as _extracted_apply_from_wb_explainability,
    _build_alpha_proxy_economics_meta as _extracted_build_alpha_proxy_economics_meta,
    _build_from_wb_explainability_inputs as _extracted_build_from_wb_explainability_inputs,
    _build_explanation_meta as _extracted_build_explanation_meta,
    _build_explanation_steps as _extracted_build_explanation_steps,
    _build_explanation_warnings as _extracted_build_explanation_warnings,
    _finalize_from_wb_explainability as _extracted_finalize_from_wb_explainability,
    _apply_explainability_mode,
)
from app.services.planning_production_order_elastic import (
    _apply_elastic_min_batch_uplift as _extracted_apply_elastic_min_batch_uplift,
    _resolve_elastic_binding_scope as _extracted_resolve_elastic_binding_scope,
)
from app.services.planning_production_order_raw_stock import (
    _estimate_competition_aware_raw_bundle_stock as _extracted_estimate_competition_aware_raw_bundle_stock,
)
from app.services.planning_production_order_math import (
    _add_units_for_color as _extracted_add_units_for_color,
    _allocate_units as _extracted_allocate_units,
    _ceil_to_int as _extracted_ceil_to_int,
    _normalize_weights as _extracted_normalize_weights,
)
from app.services.planning_production_order_inputs import (
    _PreparedProductionOrderInputs as _extracted_PreparedProductionOrderInputs,
    _prepare_production_order_inputs as _extracted_prepare_production_order_inputs,
)
from app.services.planning_production_order_layer1_summary_application import (
    _Layer1SummaryApplicationResult as _extracted_Layer1SummaryApplicationResult,
    _apply_production_order_layer1_summary as _extracted_apply_production_order_layer1_summary,
)
from app.services.planning_production_order_layer2_allocation_application import (
    _Layer2AllocationApplicationResult as _extracted_Layer2AllocationApplicationResult,
    _apply_production_order_layer2_allocation as _extracted_apply_production_order_layer2_allocation,
)
from app.services.planning_production_order_layer2_summary_application import (
    _Layer2SummaryApplicationResult as _extracted_Layer2SummaryApplicationResult,
    _apply_production_order_layer2_summary as _extracted_apply_production_order_layer2_summary,
)
from app.services.planning_production_order_layer3_application import (
    _Layer3ApplicationResult as _extracted_Layer3ApplicationResult,
    _apply_production_order_layer3 as _extracted_apply_production_order_layer3,
)
from app.services.planning_production_order_line_requirements_application import (
    _LineRequirementsApplicationResult as _extracted_LineRequirementsApplicationResult,
    _apply_production_order_line_requirements as _extracted_apply_production_order_line_requirements,
)
from app.services.planning_production_order_line_requirements import (
    _LineRequirementsPlan as _extracted_LineRequirementsPlan,
    _build_line_requirements_plan as _extracted_build_line_requirements_plan,
)
from app.services.planning_production_order_constraint_application import (
    _ConstraintApplicationResult as _extracted_ConstraintApplicationResult,
    _apply_production_order_constraints as _extracted_apply_production_order_constraints,
)
from app.services.planning_production_order_candidate_lines_application import (
    _CandidateLinesApplicationResult as _extracted_CandidateLinesApplicationResult,
    _apply_production_order_candidate_lines as _extracted_apply_production_order_candidate_lines,
)
from app.services.planning_production_order_candidate_lines import (
    _build_candidate_lines as _extracted_build_candidate_lines,
)
from app.services.planning_production_order_capital_application import (
    _CapitalApplicationResult as _extracted_CapitalApplicationResult,
    _apply_production_order_capital_constraints as _extracted_apply_production_order_capital_constraints,
)
from app.services.planning_production_order_capital_unpack_application import (
    _CapitalUnpackApplicationResult as _extracted_CapitalUnpackApplicationResult,
    _apply_production_order_capital_unpack as _extracted_apply_production_order_capital_unpack,
)
from app.services.planning_production_order_layer4_application import (
    _Layer4ApplicationResult as _extracted_Layer4ApplicationResult,
    _apply_production_order_layer4_analysis as _extracted_apply_production_order_layer4_analysis,
)
from app.services.planning_production_order_layer4_unpack_application import (
    _Layer4UnpackApplicationResult as _extracted_Layer4UnpackApplicationResult,
    _apply_production_order_layer4_unpack as _extracted_apply_production_order_layer4_unpack,
)
from app.services.planning_production_order_layer5_application import (
    _Layer5ApplicationResult as _extracted_Layer5ApplicationResult,
    _apply_production_order_layer5_analysis as _extracted_apply_production_order_layer5_analysis,
)
from app.services.planning_production_order_layer5_unpack_application import (
    _Layer5UnpackApplicationResult as _extracted_Layer5UnpackApplicationResult,
    _apply_production_order_layer5_unpack as _extracted_apply_production_order_layer5_unpack,
)
from app.services.planning_production_order_scope_recommendation import (
    _ScopeRecommendationResult as _extracted_ScopeRecommendationResult,
    _apply_production_order_scope_and_recommendation as _extracted_apply_production_order_scope_and_recommendation,
)
from app.services.planning_production_order_scope_recommendation_unpack_application import (
    _ScopeRecommendationUnpackApplicationResult as _extracted_ScopeRecommendationUnpackApplicationResult,
    _apply_production_order_scope_recommendation_unpack as _extracted_apply_production_order_scope_recommendation_unpack,
)
from app.services.planning_production_order_explanation_warning_application import (
    _ExplanationWarningApplicationResult as _extracted_ExplanationWarningApplicationResult,
    _apply_production_order_explanation_warnings as _extracted_apply_production_order_explanation_warnings,
)
from app.services.planning_production_order_explanation_warning_unpack_application import (
    _ExplanationWarningUnpackApplicationResult as _extracted_ExplanationWarningUnpackApplicationResult,
    _apply_production_order_explanation_warning_unpack as _extracted_apply_production_order_explanation_warning_unpack,
)
from app.services.planning_production_order_alpha_proxy_application import (
    _AlphaProxyApplicationResult as _extracted_AlphaProxyApplicationResult,
    _apply_production_order_alpha_proxy_economics as _extracted_apply_production_order_alpha_proxy_economics,
)
from app.services.planning_production_order_alpha_proxy_unpack_application import (
    _AlphaProxyUnpackApplicationResult as _extracted_AlphaProxyUnpackApplicationResult,
    _apply_production_order_alpha_proxy_unpack as _extracted_apply_production_order_alpha_proxy_unpack,
)
from app.services.planning_production_order_explanation_application import (
    _ExplanationApplicationResult as _extracted_ExplanationApplicationResult,
    _apply_production_order_explanation as _extracted_apply_production_order_explanation,
)
from app.services.planning_production_order_explanation_unpack_application import (
    _ExplanationUnpackApplicationResult as _extracted_ExplanationUnpackApplicationResult,
    _apply_production_order_explanation_unpack as _extracted_apply_production_order_explanation_unpack,
)
from app.services.planning_production_order_explainability_mode_application import (
    _ExplainabilityModeApplicationResult as _extracted_ExplainabilityModeApplicationResult,
    _apply_production_order_explainability_mode as _extracted_apply_production_order_explainability_mode,
)
from app.services.planning_production_order_explainability_mode_unpack_application import (
    _ExplainabilityModeUnpackApplicationResult as _extracted_ExplainabilityModeUnpackApplicationResult,
    _apply_production_order_explainability_mode_unpack as _extracted_apply_production_order_explainability_mode_unpack,
)
from app.services.planning_production_order_response_application import (
    _ResponseApplicationResult as _extracted_ResponseApplicationResult,
    _apply_production_order_response as _extracted_apply_production_order_response,
)
from app.services.planning_production_order_horizon_application import (
    _HorizonApplicationResult as _extracted_HorizonApplicationResult,
    _apply_production_order_horizon as _extracted_apply_production_order_horizon,
)
from app.services.planning_production_order_risk_application import (
    _RiskApplicationResult as _extracted_RiskApplicationResult,
    _apply_production_order_risk_level as _extracted_apply_production_order_risk_level,
)
from app.services.planning_production_order_resource_allocation_application import (
    _ResourceAllocationApplicationResult as _extracted_ResourceAllocationApplicationResult,
    _apply_production_order_resource_allocation as _extracted_apply_production_order_resource_allocation,
)
from app.services.planning_production_order_skip_application import (
    _SkipApplicationResult as _extracted_SkipApplicationResult,
    _apply_production_order_skip as _extracted_apply_production_order_skip,
)
from app.services.planning_production_order_scope import (
    _build_physical_scope_contract as _extracted_build_physical_scope_contract,
    _build_arrival_horizon_projection as _extracted_build_arrival_horizon_projection,
    build_physical_scope_and_arrival_projection,
)
from app.services.planning_production_order_settings import (
    _EffectiveSettings as _extracted_EffectiveSettings,
    _build_effective_settings as _extracted_build_effective_settings,
    _load_admin_in_flight_defaults as _extracted_load_admin_in_flight_defaults,
    _load_admin_size_weights as _extracted_load_admin_size_weights,
)
from app.services.planning_production_order_settings_loading_application import (
    _SettingsLoadingApplicationResult as _extracted_SettingsLoadingApplicationResult,
    _apply_production_order_settings_loading as _extracted_apply_production_order_settings_loading,
)
from app.services.planning_production_order_settings_resolution_application import (
    _SettingsResolutionApplicationResult as _extracted_SettingsResolutionApplicationResult,
    _apply_production_order_settings_resolution as _extracted_apply_production_order_settings_resolution,
)
from app.services.planning_production_order_supply_policy import (
    _compute_economic_buffer_days as _extracted_compute_economic_buffer_days,
    _estimate_effective_in_flight_qty as _extracted_estimate_effective_in_flight_qty,
    _in_flight_stage_factor as _extracted_in_flight_stage_factor,
)
from app.services.planning_production_order_constraints import (
    RESOURCE_ALLOCATION_CONTRACT_VERSION as EXTRACTED_RESOURCE_ALLOCATION_CONTRACT_VERSION,
    SHARED_COLOR_POOL_DEFAULT_OBSERVATION_WINDOW_DAYS as EXTRACTED_SHARED_COLOR_POOL_DEFAULT_OBSERVATION_WINDOW_DAYS,
    SHARED_COLOR_POOL_SOURCE as EXTRACTED_SHARED_COLOR_POOL_SOURCE,
    _apply_shared_color_pool_fabric_min_batches as _extracted_apply_shared_color_pool_fabric_min_batches,
    _build_competition_aware_resource_allocation as _extracted_build_competition_aware_resource_allocation,
    _build_resource_allocation_contract_summary as _extracted_build_resource_allocation_contract_summary,
    _build_shared_color_pool_snapshot as _extracted_build_shared_color_pool_snapshot,
)
from app.services.planning_production_order_capital import (
    CAPITAL_CONSTRAINT_CONTRACT_VERSION as EXTRACTED_CAPITAL_CONSTRAINT_CONTRACT_VERSION,
    LAYER4_CONTRACT_VERSION as EXTRACTED_LAYER4_CONTRACT_VERSION,
    LAYER4_SCENARIO_FACTORS as EXTRACTED_LAYER4_SCENARIO_FACTORS,
    LAYER4_SCENARIO_ORDER as EXTRACTED_LAYER4_SCENARIO_ORDER,
    _bounded_unit_float as _extracted_bounded_unit_float,
    _apply_capital_constraint_to_candidate_lines as _extracted_apply_capital_constraint_to_candidate_lines,
    _build_capital_constraint_contract_summary as _extracted_build_capital_constraint_contract_summary,
    _build_capital_gap_summary as _extracted_build_capital_gap_summary,
    _build_layer4_aggregate_deltas as _extracted_build_layer4_aggregate_deltas,
    _build_layer4_contract_summary as _extracted_build_layer4_contract_summary,
    _build_layer4_scenarios as _extracted_build_layer4_scenarios,
    _build_line_objective_capital_rankings as _extracted_build_line_objective_capital_rankings,
    _compute_objective_components as _extracted_compute_objective_components,
)
from app.services.planning_production_order_decision import (
    LAYER1_CONTRACT_VERSION as EXTRACTED_LAYER1_CONTRACT_VERSION,
    LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD as EXTRACTED_LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD,
    LAYER2_ALLOCATION_METHOD as EXTRACTED_LAYER2_ALLOCATION_METHOD,
    LAYER2_ALLOCATION_METHOD_CANONICAL as EXTRACTED_LAYER2_ALLOCATION_METHOD_CANONICAL,
    LAYER2_CONTRACT_VERSION as EXTRACTED_LAYER2_CONTRACT_VERSION,
    LAYER2_DECISION_GATE_CANONICAL as EXTRACTED_LAYER2_DECISION_GATE_CANONICAL,
    LAYER2_DECISION_GATE_LEGACY as EXTRACTED_LAYER2_DECISION_GATE_LEGACY,
    LAYER2_DECISION_REASON_CANONICAL_BY_DECISION as EXTRACTED_LAYER2_DECISION_REASON_CANONICAL_BY_DECISION,
    LAYER2_DECISION_REASON_LEGACY_BY_DECISION as EXTRACTED_LAYER2_DECISION_REASON_LEGACY_BY_DECISION,
    LAYER2_DECISION_REASON_OBJECTIVE_BY_DECISION as EXTRACTED_LAYER2_DECISION_REASON_OBJECTIVE_BY_DECISION,
    LAYER2_EXPECTED_GROSS_PROFIT_GATE_LEGACY as EXTRACTED_LAYER2_EXPECTED_GROSS_PROFIT_GATE_LEGACY,
    LAYER2_LEGACY_ALIAS_DEPRECATION_POLICY as EXTRACTED_LAYER2_LEGACY_ALIAS_DEPRECATION_POLICY,
    LAYER2_LEGACY_ALIAS_FIELD_REPLACEMENTS as EXTRACTED_LAYER2_LEGACY_ALIAS_FIELD_REPLACEMENTS,
    LAYER2_LEGACY_DECISION_GATE_ALIASES as EXTRACTED_LAYER2_LEGACY_DECISION_GATE_ALIASES,
    LAYER2_LEGACY_GATE_ALIAS_DEPRECATION_WINDOW as EXTRACTED_LAYER2_LEGACY_GATE_ALIAS_DEPRECATION_WINDOW,
    LAYER2_NEAR_TIE_OBJECTIVE_GAP_THRESHOLD as EXTRACTED_LAYER2_NEAR_TIE_OBJECTIVE_GAP_THRESHOLD,
    LAYER2_NEAR_TIE_PROFIT_GAP_THRESHOLD as EXTRACTED_LAYER2_NEAR_TIE_PROFIT_GAP_THRESHOLD,
    _build_layer1_contract_summary as _extracted_build_layer1_contract_summary,
    _build_layer1_stock_health_metrics as _extracted_build_layer1_stock_health_metrics,
    _build_layer2_allocation_decisions as _extracted_build_layer2_allocation_decisions,
    _build_layer2_contract_summary as _extracted_build_layer2_contract_summary,
    _build_layer2_decision_quality_summary as _extracted_build_layer2_decision_quality_summary,
    _build_layer2_legacy_alias_deprecation_plan as _extracted_build_layer2_legacy_alias_deprecation_plan,
)
from app.services.planning_production_order_recommendation import (
    _build_alternatives as _extracted_build_alternatives,
    build_recommendation_and_alternatives as _extracted_build_recommendation_and_alternatives,
    _choose_action as _extracted_choose_action,
)
from app.services.planning_production_order_layer_proxy import (
    LAYER2_CAPITAL_COST_RATE as EXTRACTED_LAYER2_CAPITAL_COST_RATE,
    LAYER2_OVERSTOCK_PENALTY_WEIGHT as EXTRACTED_LAYER2_OVERSTOCK_PENALTY_WEIGHT,
    LAYER2_STOCKOUT_PENALTY_WEIGHT as EXTRACTED_LAYER2_STOCKOUT_PENALTY_WEIGHT,
    LAYER3_OVERSTOCK_DAMPEN_MAX as EXTRACTED_LAYER3_OVERSTOCK_DAMPEN_MAX,
    LAYER3_STOCKOUT_BOOST_MAX as EXTRACTED_LAYER3_STOCKOUT_BOOST_MAX,
    LAYER5_ACCELERATE_ACTION_COST_RATE as EXTRACTED_LAYER5_ACCELERATE_ACTION_COST_RATE,
    LAYER5_ACCELERATE_PRODUCTION_RISK_THRESHOLD as EXTRACTED_LAYER5_ACCELERATE_PRODUCTION_RISK_THRESHOLD,
    LAYER5_PRICE_SLOWDOWN_LOST_VOLUME_RATE as EXTRACTED_LAYER5_PRICE_SLOWDOWN_LOST_VOLUME_RATE,
    LAYER5_REDUCE_ORDER_MARGINAL_PROFIT_RATE as EXTRACTED_LAYER5_REDUCE_ORDER_MARGINAL_PROFIT_RATE,
    LAYER5_UNAVOIDABLE_STOCKOUT_RISK_THRESHOLD as EXTRACTED_LAYER5_UNAVOIDABLE_STOCKOUT_RISK_THRESHOLD,
    _EffectiveLayerProxySettings,
    _resolve_layer_proxy_settings,
)
from app.services.planning_production_order_layer3 import (
    LAYER3_CALIBRATION_METHOD as EXTRACTED_LAYER3_CALIBRATION_METHOD,
    LAYER3_CONTRACT_VERSION as EXTRACTED_LAYER3_CONTRACT_VERSION,
    LAYER3_FACTOR_BOUNDS as EXTRACTED_LAYER3_FACTOR_BOUNDS,
    LAYER3_OVERSTOCK_WEIGHT_BY_DECISION as EXTRACTED_LAYER3_OVERSTOCK_WEIGHT_BY_DECISION,
    LAYER3_PURCHASE_FACTOR_BY_DECISION as EXTRACTED_LAYER3_PURCHASE_FACTOR_BY_DECISION,
    LAYER3_STOCKOUT_WEIGHT_BY_DECISION as EXTRACTED_LAYER3_STOCKOUT_WEIGHT_BY_DECISION,
    _apply_layer3_purchase_shaping as _extracted_apply_layer3_purchase_shaping,
    _build_layer3_contract_summary as _extracted_build_layer3_contract_summary,
)
from app.services.planning_production_order_layer5 import (
    LAYER5_CONTRACT_VERSION as EXTRACTED_LAYER5_CONTRACT_VERSION,
    LAYER5_PRICE_SLOWDOWN_RISK_THRESHOLD as EXTRACTED_LAYER5_PRICE_SLOWDOWN_RISK_THRESHOLD,
    _build_layer5_contract_summary as _extracted_build_layer5_contract_summary,
    _build_layer5_intervention_signals as _extracted_build_layer5_intervention_signals,
    _build_layer5_threshold_clamped_warning as _extracted_build_layer5_threshold_clamped_warning,
)
from app.services.planning_production_order_operator_contracts import (
    CAPITAL_GOVERNANCE_MODE_SAFE_DEFAULT as EXTRACTED_CAPITAL_GOVERNANCE_MODE_SAFE_DEFAULT,
    CAPITAL_GOVERNANCE_MODE_STRICT as EXTRACTED_CAPITAL_GOVERNANCE_MODE_STRICT,
    CAPITAL_GOVERNANCE_SOURCE_SAFE_DEFAULT as EXTRACTED_CAPITAL_GOVERNANCE_SOURCE_SAFE_DEFAULT,
    CAPITAL_GOVERNANCE_STATUS_SAFE_DEFAULT_APPLIED as EXTRACTED_CAPITAL_GOVERNANCE_STATUS_SAFE_DEFAULT_APPLIED,
    CAPITAL_GOVERNANCE_WARNING_CODE_SAFE_DEFAULT as EXTRACTED_CAPITAL_GOVERNANCE_WARNING_CODE_SAFE_DEFAULT,
    _build_available_capital_safe_default_warning as _extracted_build_available_capital_safe_default_warning,
    _build_direct_missing_bundle_recipe_detail as _extracted_build_direct_missing_bundle_recipe_detail,
    _build_direct_missing_sku_scope_detail as _extracted_build_direct_missing_sku_scope_detail,
    _build_from_wb_freshness_failure_detail as _extracted_build_from_wb_freshness_failure_detail,
    _build_from_wb_missing_requested_bundle_type_detail as _extracted_build_from_wb_missing_requested_bundle_type_detail,
    _build_from_wb_no_mapping_detail as _extracted_build_from_wb_no_mapping_detail,
    _build_layer_proxy_invalid_values_ignored_warning as _extracted_build_layer_proxy_invalid_values_ignored_warning,
    _build_missing_available_capital_strict_detail as _extracted_build_missing_available_capital_strict_detail,
    _build_shortage_wait_blocked_by_capital_constraint_warning as _extracted_build_shortage_wait_blocked_by_capital_constraint_warning,
)
from app.services.planning_production_order_from_wb import (
    FROM_WB_PRICE_ANOMALY_MAX_DEVIATION as EXTRACTED_FROM_WB_PRICE_ANOMALY_MAX_DEVIATION,
    FROM_WB_TARIFFS_API_BASE_URL as EXTRACTED_FROM_WB_TARIFFS_API_BASE_URL,
    FROM_WB_TARIFFS_COMMISSION_PATH as EXTRACTED_FROM_WB_TARIFFS_COMMISSION_PATH,
    FROM_WB_TARIFFS_COMMISSION_SOURCE as EXTRACTED_FROM_WB_TARIFFS_COMMISSION_SOURCE,
    FROM_WB_TARIFFS_HTTP_TIMEOUT_SECONDS as EXTRACTED_FROM_WB_TARIFFS_HTTP_TIMEOUT_SECONDS,
    _build_from_wb_preflight_context as _extracted_build_from_wb_preflight_context,
    _build_production_order_proposal_from_wb_response as _extracted_build_production_order_proposal_from_wb_response,
    _build_from_wb_proposal_request as _extracted_build_from_wb_proposal_request,
    _build_from_wb_runtime_economic_overrides as _extracted_build_from_wb_runtime_economic_overrides,
    _get_wb_mapped_bundle_type_ids as _extracted_get_wb_mapped_bundle_type_ids,
    _load_from_wb_observed_commission_calibration as _extracted_load_from_wb_observed_commission_calibration,
    _load_from_wb_observed_price_calibration as _extracted_load_from_wb_observed_price_calibration,
    _load_wb_bundle_daily_sales as _extracted_load_wb_bundle_daily_sales,
    _load_wb_bundle_stock as _extracted_load_wb_bundle_stock,
    _load_wb_bundle_stock_updated_at_by_bundle as _extracted_load_wb_bundle_stock_updated_at_by_bundle,
    _normalize_from_wb_commission_ratio as _extracted_normalize_from_wb_commission_ratio,
    _resolve_bundle_type_ids_for_from_wb as _extracted_resolve_bundle_type_ids_for_from_wb,
    _summarize_from_wb_price_samples as _extracted_summarize_from_wb_price_samples,
)
from app.services.planning_production_order_freshness import (
    FROM_WB_SALES_STALE_AFTER_DAYS as EXTRACTED_FROM_WB_SALES_STALE_AFTER_DAYS,
    FROM_WB_STOCK_STALE_AFTER_DAYS as EXTRACTED_FROM_WB_STOCK_STALE_AFTER_DAYS,
    build_from_wb_freshness_next_steps,
    build_from_wb_freshness_snapshot as _extracted_build_from_wb_freshness_snapshot,
    _raise_from_wb_strict_freshness_failure_if_needed as _extracted_raise_from_wb_strict_freshness_failure_if_needed,
    _resolve_from_wb_freshness_thresholds as _extracted_resolve_from_wb_freshness_thresholds,
)

# Ownership: this module keeps orchestration, shared estimators, and response assembly.

FROM_WB_SALES_STALE_AFTER_DAYS = EXTRACTED_FROM_WB_SALES_STALE_AFTER_DAYS
FROM_WB_STOCK_STALE_AFTER_DAYS = EXTRACTED_FROM_WB_STOCK_STALE_AFTER_DAYS
FROM_WB_OBSERVED_ECONOMIC_SOURCE = EXTRACTED_FROM_WB_OBSERVED_ECONOMIC_SOURCE
FROM_WB_TARIFFS_COMMISSION_SOURCE = EXTRACTED_FROM_WB_TARIFFS_COMMISSION_SOURCE
FROM_WB_PRICE_ANOMALY_MAX_DEVIATION = EXTRACTED_FROM_WB_PRICE_ANOMALY_MAX_DEVIATION
FROM_WB_TARIFFS_API_BASE_URL = EXTRACTED_FROM_WB_TARIFFS_API_BASE_URL
FROM_WB_TARIFFS_COMMISSION_PATH = EXTRACTED_FROM_WB_TARIFFS_COMMISSION_PATH
FROM_WB_TARIFFS_HTTP_TIMEOUT_SECONDS = EXTRACTED_FROM_WB_TARIFFS_HTTP_TIMEOUT_SECONDS
SHARED_COLOR_POOL_SOURCE = EXTRACTED_SHARED_COLOR_POOL_SOURCE
SHARED_COLOR_POOL_DEFAULT_OBSERVATION_WINDOW_DAYS = EXTRACTED_SHARED_COLOR_POOL_DEFAULT_OBSERVATION_WINDOW_DAYS
LAYER2_ALLOCATION_METHOD = EXTRACTED_LAYER2_ALLOCATION_METHOD
LAYER2_ALLOCATION_METHOD_CANONICAL = EXTRACTED_LAYER2_ALLOCATION_METHOD_CANONICAL
LAYER2_DECISION_GATE_LEGACY = EXTRACTED_LAYER2_DECISION_GATE_LEGACY
LAYER2_DECISION_GATE_CANONICAL = EXTRACTED_LAYER2_DECISION_GATE_CANONICAL
LAYER2_DECISION_REASON_LEGACY_BY_DECISION = EXTRACTED_LAYER2_DECISION_REASON_LEGACY_BY_DECISION
LAYER2_DECISION_REASON_CANONICAL_BY_DECISION = EXTRACTED_LAYER2_DECISION_REASON_CANONICAL_BY_DECISION
LAYER2_DECISION_REASON_OBJECTIVE_BY_DECISION = EXTRACTED_LAYER2_DECISION_REASON_OBJECTIVE_BY_DECISION
ASSORTI_CLASSIFICATION_SOURCE = EXTRACTED_ASSORTI_CLASSIFICATION_SOURCE
ASSORTI_CLASSIFICATION_ADMIN_FALLBACK_SOURCE = EXTRACTED_ASSORTI_CLASSIFICATION_ADMIN_FALLBACK_SOURCE
ASSORTI_CLASSIFICATION_GLOBAL_FALLBACK_SOURCE = EXTRACTED_ASSORTI_CLASSIFICATION_GLOBAL_FALLBACK_SOURCE
ASSORTI_CLASSIFICATION_MISSING_SOURCE = EXTRACTED_ASSORTI_CLASSIFICATION_MISSING_SOURCE
EXPLAINABILITY_MODE_FULL = "full"
EXPLAINABILITY_MODE_COMPACT = EXTRACTED_EXPLAINABILITY_MODE_COMPACT
LAYER_PROXY_VALUE_SOURCE = EXTRACTED_LAYER_PROXY_VALUE_SOURCE
ECONOMICS_FORMULA_VERSION = EXTRACTED_ECONOMICS_FORMULA_VERSION
ECONOMICS_DEFAULT_PRODUCTION_COST_PER_UNIT = EXTRACTED_ECONOMICS_DEFAULT_PRODUCTION_COST_PER_UNIT
ECONOMICS_DEFAULT_LOGISTICS_COST_PER_UNIT = EXTRACTED_ECONOMICS_DEFAULT_LOGISTICS_COST_PER_UNIT
ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_MAIN = EXTRACTED_ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_MAIN
ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_ASSORTI = EXTRACTED_ECONOMICS_DEFAULT_WB_COMMISSION_PERCENT_ASSORTI
ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_MAIN = EXTRACTED_ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_MAIN
ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_ASSORTI = EXTRACTED_ECONOMICS_DEFAULT_AVERAGE_REALIZED_PRICE_ASSORTI
ECONOMICS_TRUST_LEVEL_TRUSTED = EXTRACTED_ECONOMICS_TRUST_LEVEL_TRUSTED
ECONOMICS_TRUST_LEVEL_PARTIAL = EXTRACTED_ECONOMICS_TRUST_LEVEL_PARTIAL
ECONOMICS_TRUST_LEVEL_UNTRUSTED = EXTRACTED_ECONOMICS_TRUST_LEVEL_UNTRUSTED
ECONOMICS_TRUST_KEY_FIELDS = EXTRACTED_ECONOMICS_TRUST_KEY_FIELDS
ECONOMICS_TRUST_UNTRUSTED_CODE_DEFAULT_THRESHOLD = EXTRACTED_ECONOMICS_TRUST_UNTRUSTED_CODE_DEFAULT_THRESHOLD
ECONOMICS_TRUST_WARNING_CODE_UNTRUSTED = EXTRACTED_ECONOMICS_TRUST_WARNING_CODE_UNTRUSTED
ECONOMICS_TRUST_WARNING_CODE_PARTIAL = EXTRACTED_ECONOMICS_TRUST_WARNING_CODE_PARTIAL
CAPITAL_CONSTRAINT_STATUS_MISSING_STRICT = EXTRACTED_CAPITAL_CONSTRAINT_STATUS_MISSING_STRICT
CAPITAL_GOVERNANCE_MODE_STRICT = EXTRACTED_CAPITAL_GOVERNANCE_MODE_STRICT
CAPITAL_GOVERNANCE_MODE_SAFE_DEFAULT = EXTRACTED_CAPITAL_GOVERNANCE_MODE_SAFE_DEFAULT
CAPITAL_GOVERNANCE_WARNING_CODE_SAFE_DEFAULT = EXTRACTED_CAPITAL_GOVERNANCE_WARNING_CODE_SAFE_DEFAULT
CAPITAL_GOVERNANCE_STATUS_SAFE_DEFAULT_APPLIED = EXTRACTED_CAPITAL_GOVERNANCE_STATUS_SAFE_DEFAULT_APPLIED
CAPITAL_GOVERNANCE_SOURCE_SAFE_DEFAULT = EXTRACTED_CAPITAL_GOVERNANCE_SOURCE_SAFE_DEFAULT
LAYER2_NEAR_TIE_OBJECTIVE_GAP_THRESHOLD = EXTRACTED_LAYER2_NEAR_TIE_OBJECTIVE_GAP_THRESHOLD
LAYER2_NEAR_TIE_PROFIT_GAP_THRESHOLD = EXTRACTED_LAYER2_NEAR_TIE_PROFIT_GAP_THRESHOLD
LAYER2_CAPITAL_COST_RATE = EXTRACTED_LAYER2_CAPITAL_COST_RATE
LAYER2_STOCKOUT_PENALTY_WEIGHT = EXTRACTED_LAYER2_STOCKOUT_PENALTY_WEIGHT
LAYER2_OVERSTOCK_PENALTY_WEIGHT = EXTRACTED_LAYER2_OVERSTOCK_PENALTY_WEIGHT
LAYER2_LEGACY_GATE_ALIAS_DEPRECATION_WINDOW = EXTRACTED_LAYER2_LEGACY_GATE_ALIAS_DEPRECATION_WINDOW
LAYER2_EXPECTED_GROSS_PROFIT_GATE_LEGACY = EXTRACTED_LAYER2_EXPECTED_GROSS_PROFIT_GATE_LEGACY
LAYER2_LEGACY_ALIAS_DEPRECATION_POLICY = EXTRACTED_LAYER2_LEGACY_ALIAS_DEPRECATION_POLICY
LAYER2_LEGACY_DECISION_GATE_ALIASES = EXTRACTED_LAYER2_LEGACY_DECISION_GATE_ALIASES
LAYER2_LEGACY_ALIAS_FIELD_REPLACEMENTS = EXTRACTED_LAYER2_LEGACY_ALIAS_FIELD_REPLACEMENTS
LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD = EXTRACTED_LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD
LAYER1_CONTRACT_VERSION = EXTRACTED_LAYER1_CONTRACT_VERSION
LAYER2_CONTRACT_VERSION = EXTRACTED_LAYER2_CONTRACT_VERSION
LAYER3_CONTRACT_VERSION = EXTRACTED_LAYER3_CONTRACT_VERSION
LAYER3_PURCHASE_FACTOR_BY_DECISION = EXTRACTED_LAYER3_PURCHASE_FACTOR_BY_DECISION
LAYER3_CALIBRATION_METHOD = EXTRACTED_LAYER3_CALIBRATION_METHOD
LAYER3_STOCKOUT_BOOST_MAX = EXTRACTED_LAYER3_STOCKOUT_BOOST_MAX
LAYER3_OVERSTOCK_DAMPEN_MAX = EXTRACTED_LAYER3_OVERSTOCK_DAMPEN_MAX
LAYER3_STOCKOUT_WEIGHT_BY_DECISION = EXTRACTED_LAYER3_STOCKOUT_WEIGHT_BY_DECISION
LAYER3_OVERSTOCK_WEIGHT_BY_DECISION = EXTRACTED_LAYER3_OVERSTOCK_WEIGHT_BY_DECISION
LAYER3_FACTOR_BOUNDS = EXTRACTED_LAYER3_FACTOR_BOUNDS
LAYER4_SCENARIO_ORDER = EXTRACTED_LAYER4_SCENARIO_ORDER
LAYER4_CONTRACT_VERSION = EXTRACTED_LAYER4_CONTRACT_VERSION
LAYER4_SCENARIO_FACTORS = EXTRACTED_LAYER4_SCENARIO_FACTORS
CAPITAL_CONSTRAINT_CONTRACT_VERSION = EXTRACTED_CAPITAL_CONSTRAINT_CONTRACT_VERSION
RESOURCE_ALLOCATION_CONTRACT_VERSION = EXTRACTED_RESOURCE_ALLOCATION_CONTRACT_VERSION
LAYER5_CONTRACT_VERSION = EXTRACTED_LAYER5_CONTRACT_VERSION
LAYER5_UNAVOIDABLE_STOCKOUT_RISK_THRESHOLD = EXTRACTED_LAYER5_UNAVOIDABLE_STOCKOUT_RISK_THRESHOLD
LAYER5_ACCELERATE_PRODUCTION_RISK_THRESHOLD = EXTRACTED_LAYER5_ACCELERATE_PRODUCTION_RISK_THRESHOLD
LAYER5_PRICE_SLOWDOWN_RISK_THRESHOLD = EXTRACTED_LAYER5_PRICE_SLOWDOWN_RISK_THRESHOLD
LAYER5_ACCELERATE_ACTION_COST_RATE = EXTRACTED_LAYER5_ACCELERATE_ACTION_COST_RATE
LAYER5_PRICE_SLOWDOWN_LOST_VOLUME_RATE = EXTRACTED_LAYER5_PRICE_SLOWDOWN_LOST_VOLUME_RATE
LAYER5_REDUCE_ORDER_MARGINAL_PROFIT_RATE = EXTRACTED_LAYER5_REDUCE_ORDER_MARGINAL_PROFIT_RATE

_build_physical_scope_contract = _extracted_build_physical_scope_contract
_build_arrival_horizon_projection = _extracted_build_arrival_horizon_projection
_in_flight_stage_factor = _extracted_in_flight_stage_factor
_estimate_effective_in_flight_qty = _extracted_estimate_effective_in_flight_qty
_compute_economic_buffer_days = _extracted_compute_economic_buffer_days
_build_alpha_proxy_economics_meta = _extracted_build_alpha_proxy_economics_meta
_build_from_wb_explainability_inputs = _extracted_build_from_wb_explainability_inputs
_build_explanation_meta = _extracted_build_explanation_meta
_build_explanation_steps = _extracted_build_explanation_steps
_build_explanation_warnings = _extracted_build_explanation_warnings
_apply_from_wb_explainability = _extracted_apply_from_wb_explainability
_finalize_from_wb_explainability = _extracted_finalize_from_wb_explainability
_resolve_economic_trust_and_capital_governance = _extracted_resolve_economic_trust_and_capital_governance

_build_resource_allocation_contract_summary = _extracted_build_resource_allocation_contract_summary
_build_competition_aware_resource_allocation = _extracted_build_competition_aware_resource_allocation
_build_shared_color_pool_snapshot = _extracted_build_shared_color_pool_snapshot
_apply_shared_color_pool_fabric_min_batches = _extracted_apply_shared_color_pool_fabric_min_batches

_build_layer1_stock_health_metrics = _extracted_build_layer1_stock_health_metrics
_build_layer1_contract_summary = _extracted_build_layer1_contract_summary
_build_layer2_allocation_decisions = _extracted_build_layer2_allocation_decisions
_build_layer2_contract_summary = _extracted_build_layer2_contract_summary
_build_layer2_decision_quality_summary = _extracted_build_layer2_decision_quality_summary
_build_layer2_legacy_alias_deprecation_plan = _extracted_build_layer2_legacy_alias_deprecation_plan

_apply_layer3_purchase_shaping = _extracted_apply_layer3_purchase_shaping
_build_layer3_contract_summary = _extracted_build_layer3_contract_summary

_build_layer5_intervention_signals = _extracted_build_layer5_intervention_signals
_build_layer5_contract_summary = _extracted_build_layer5_contract_summary
_build_layer5_threshold_clamped_warning = _extracted_build_layer5_threshold_clamped_warning

_build_from_wb_freshness_failure_detail = _extracted_build_from_wb_freshness_failure_detail
_build_direct_missing_bundle_recipe_detail = _extracted_build_direct_missing_bundle_recipe_detail
_build_direct_missing_sku_scope_detail = _extracted_build_direct_missing_sku_scope_detail
_build_article_not_found_detail = _extracted_build_article_not_found_detail
_require_article = _extracted_require_article
_build_missing_available_capital_strict_detail = _extracted_build_missing_available_capital_strict_detail
_build_available_capital_safe_default_warning = _extracted_build_available_capital_safe_default_warning
_build_layer_proxy_invalid_values_ignored_warning = _extracted_build_layer_proxy_invalid_values_ignored_warning
_build_shortage_wait_blocked_by_capital_constraint_warning = _extracted_build_shortage_wait_blocked_by_capital_constraint_warning

_build_from_wb_no_mapping_detail = _extracted_build_from_wb_no_mapping_detail
_build_from_wb_missing_requested_bundle_type_detail = _extracted_build_from_wb_missing_requested_bundle_type_detail
_build_from_wb_preflight_context = _extracted_build_from_wb_preflight_context
_build_production_order_proposal_from_wb_response = _extracted_build_production_order_proposal_from_wb_response
_build_from_wb_proposal_request = _extracted_build_from_wb_proposal_request
_build_from_wb_runtime_economic_overrides = _extracted_build_from_wb_runtime_economic_overrides
_get_wb_mapped_bundle_type_ids = _extracted_get_wb_mapped_bundle_type_ids
_resolve_bundle_type_ids_for_from_wb = _extracted_resolve_bundle_type_ids_for_from_wb
_load_wb_bundle_daily_sales = _extracted_load_wb_bundle_daily_sales
_load_wb_bundle_stock = _extracted_load_wb_bundle_stock
_load_wb_bundle_stock_updated_at_by_bundle = _extracted_load_wb_bundle_stock_updated_at_by_bundle
_summarize_from_wb_price_samples = _extracted_summarize_from_wb_price_samples
_load_from_wb_observed_price_calibration = _extracted_load_from_wb_observed_price_calibration
_normalize_from_wb_commission_ratio = _extracted_normalize_from_wb_commission_ratio
_load_from_wb_observed_commission_calibration = _extracted_load_from_wb_observed_commission_calibration

_build_line_objective_capital_rankings = _extracted_build_line_objective_capital_rankings
_apply_capital_constraint_to_candidate_lines = _extracted_apply_capital_constraint_to_candidate_lines
_build_capital_constraint_contract_summary = _extracted_build_capital_constraint_contract_summary
_build_capital_gap_summary = _extracted_build_capital_gap_summary
_build_layer4_aggregate_deltas = _extracted_build_layer4_aggregate_deltas
_build_layer4_contract_summary = _extracted_build_layer4_contract_summary
_build_layer4_scenarios = _extracted_build_layer4_scenarios
_build_recommendation_and_alternatives = _extracted_build_recommendation_and_alternatives

_AssortiApplicationResult = _extracted_AssortiApplicationResult
_apply_production_order_assorti_classification = (
    _extracted_apply_production_order_assorti_classification
)
_EffectiveSettings = _extracted_EffectiveSettings
_build_effective_settings = _extracted_build_effective_settings
_EconomicGovernanceApplicationResult = _extracted_EconomicGovernanceApplicationResult
_apply_production_order_economic_governance = (
    _extracted_apply_production_order_economic_governance
)
_SettingsLoadingApplicationResult = _extracted_SettingsLoadingApplicationResult
_apply_production_order_settings_loading = (
    _extracted_apply_production_order_settings_loading
)
_SettingsResolutionApplicationResult = _extracted_SettingsResolutionApplicationResult
_apply_production_order_settings_resolution = (
    _extracted_apply_production_order_settings_resolution
)
_load_admin_size_weights = _extracted_load_admin_size_weights
_load_admin_in_flight_defaults = _extracted_load_admin_in_flight_defaults
_PreparedProductionOrderInputs = _extracted_PreparedProductionOrderInputs
_prepare_production_order_inputs = _extracted_prepare_production_order_inputs
_Layer1SummaryApplicationResult = _extracted_Layer1SummaryApplicationResult
_apply_production_order_layer1_summary = _extracted_apply_production_order_layer1_summary
_Layer2AllocationApplicationResult = _extracted_Layer2AllocationApplicationResult
_apply_production_order_layer2_allocation = _extracted_apply_production_order_layer2_allocation
_Layer2SummaryApplicationResult = _extracted_Layer2SummaryApplicationResult
_apply_production_order_layer2_summary = _extracted_apply_production_order_layer2_summary
_Layer3ApplicationResult = _extracted_Layer3ApplicationResult
_apply_production_order_layer3 = _extracted_apply_production_order_layer3
_LineRequirementsApplicationResult = _extracted_LineRequirementsApplicationResult
_apply_production_order_line_requirements = (
    _extracted_apply_production_order_line_requirements
)
_LineRequirementsPlan = _extracted_LineRequirementsPlan
_build_line_requirements_plan = _extracted_build_line_requirements_plan
_ConstraintApplicationResult = _extracted_ConstraintApplicationResult
_apply_production_order_constraints = _extracted_apply_production_order_constraints
_CandidateLinesApplicationResult = _extracted_CandidateLinesApplicationResult
_apply_production_order_candidate_lines = _extracted_apply_production_order_candidate_lines
_build_candidate_lines = _extracted_build_candidate_lines
_CapitalApplicationResult = _extracted_CapitalApplicationResult
_apply_production_order_capital_constraints = _extracted_apply_production_order_capital_constraints
_CapitalUnpackApplicationResult = _extracted_CapitalUnpackApplicationResult
_apply_production_order_capital_unpack = _extracted_apply_production_order_capital_unpack
_Layer4ApplicationResult = _extracted_Layer4ApplicationResult
_apply_production_order_layer4_analysis = _extracted_apply_production_order_layer4_analysis
_Layer4UnpackApplicationResult = _extracted_Layer4UnpackApplicationResult
_apply_production_order_layer4_unpack = _extracted_apply_production_order_layer4_unpack
_Layer5ApplicationResult = _extracted_Layer5ApplicationResult
_apply_production_order_layer5_analysis = _extracted_apply_production_order_layer5_analysis
_Layer5UnpackApplicationResult = _extracted_Layer5UnpackApplicationResult
_apply_production_order_layer5_unpack = _extracted_apply_production_order_layer5_unpack
_ScopeRecommendationResult = _extracted_ScopeRecommendationResult
_apply_production_order_scope_and_recommendation = _extracted_apply_production_order_scope_and_recommendation
_ScopeRecommendationUnpackApplicationResult = _extracted_ScopeRecommendationUnpackApplicationResult
_apply_production_order_scope_recommendation_unpack = _extracted_apply_production_order_scope_recommendation_unpack
_ExplanationWarningApplicationResult = _extracted_ExplanationWarningApplicationResult
_apply_production_order_explanation_warnings = _extracted_apply_production_order_explanation_warnings
_ExplanationWarningUnpackApplicationResult = _extracted_ExplanationWarningUnpackApplicationResult
_apply_production_order_explanation_warning_unpack = _extracted_apply_production_order_explanation_warning_unpack
_AlphaProxyApplicationResult = _extracted_AlphaProxyApplicationResult
_apply_production_order_alpha_proxy_economics = _extracted_apply_production_order_alpha_proxy_economics
_AlphaProxyUnpackApplicationResult = _extracted_AlphaProxyUnpackApplicationResult
_apply_production_order_alpha_proxy_unpack = _extracted_apply_production_order_alpha_proxy_unpack
_ExplanationApplicationResult = _extracted_ExplanationApplicationResult
_apply_production_order_explanation = _extracted_apply_production_order_explanation
_ExplanationUnpackApplicationResult = _extracted_ExplanationUnpackApplicationResult
_apply_production_order_explanation_unpack = _extracted_apply_production_order_explanation_unpack
_ExplainabilityModeApplicationResult = _extracted_ExplainabilityModeApplicationResult
_apply_production_order_explainability_mode = _extracted_apply_production_order_explainability_mode
_ExplainabilityModeUnpackApplicationResult = _extracted_ExplainabilityModeUnpackApplicationResult
_apply_production_order_explainability_mode_unpack = _extracted_apply_production_order_explainability_mode_unpack
_HorizonApplicationResult = _extracted_HorizonApplicationResult
_apply_production_order_horizon = _extracted_apply_production_order_horizon
_RiskApplicationResult = _extracted_RiskApplicationResult
_apply_production_order_risk_level = _extracted_apply_production_order_risk_level
_ResponseApplicationResult = _extracted_ResponseApplicationResult
_apply_production_order_response = _extracted_apply_production_order_response
_ResourceAllocationApplicationResult = _extracted_ResourceAllocationApplicationResult
_apply_production_order_resource_allocation = (
    _extracted_apply_production_order_resource_allocation
)
_SkipApplicationResult = _extracted_SkipApplicationResult
_apply_production_order_skip = _extracted_apply_production_order_skip
_apply_elastic_min_batch_uplift = _extracted_apply_elastic_min_batch_uplift
_resolve_elastic_binding_scope = _extracted_resolve_elastic_binding_scope
_estimate_competition_aware_raw_bundle_stock = _extracted_estimate_competition_aware_raw_bundle_stock
_build_from_wb_freshness_snapshot = _extracted_build_from_wb_freshness_snapshot
_raise_from_wb_strict_freshness_failure_if_needed = (
    _extracted_raise_from_wb_strict_freshness_failure_if_needed
)
_resolve_from_wb_freshness_thresholds = _extracted_resolve_from_wb_freshness_thresholds
_bounded_unit_float = _extracted_bounded_unit_float
_compute_objective_components = _extracted_compute_objective_components
_ceil_to_int = _extracted_ceil_to_int
_normalize_weights = _extracted_normalize_weights
_allocate_units = _extracted_allocate_units
_add_units_for_color = _extracted_add_units_for_color

_choose_action = _extracted_choose_action
_build_alternatives = _extracted_build_alternatives
_build_recommendation_and_alternatives = _extracted_build_recommendation_and_alternatives

def build_production_order_proposal_from_wb(
    db: Session,
    request: ProductionOrderProposalFromWbRequest,
) -> ProductionOrderProposalResponse:
    return _build_production_order_proposal_from_wb_response(
        db=db,
        request=request,
        build_article_not_found_detail=_build_article_not_found_detail,
        build_from_wb_freshness_failure_detail=_build_from_wb_freshness_failure_detail,
        build_production_order_proposal=build_production_order_proposal,
        finalize_from_wb_explainability=_finalize_from_wb_explainability,
    )


def build_production_order_proposal(
    db: Session,
    request: ProductionOrderProposalRequest,
    *,
    runtime_economic_overrides: dict[str, float | None] | None = None,
    runtime_economic_source: str | None = None,
    runtime_economic_source_overrides: dict[str, str] | None = None,
    shared_color_pool_observation_window_days: int | None = None,
    shared_color_pool_as_of_date: date | None = None,
) -> ProductionOrderProposalResponse:
    now = datetime.now(timezone.utc)

    _require_article(db=db, article_id=request.article_id)

    settings_loading_application = _apply_production_order_settings_loading(
        db=db,
        article_id=request.article_id,
    )
    article_settings = settings_loading_application.article_settings
    planning_settings = settings_loading_application.planning_settings
    global_settings = settings_loading_application.global_settings

    settings_resolution_application = _apply_production_order_settings_resolution(
        article_settings=article_settings,
        planning_settings=planning_settings,
        global_settings=global_settings,
        overrides=request.overrides,
        runtime_economic_overrides=runtime_economic_overrides,
        runtime_economic_source=runtime_economic_source,
        runtime_economic_source_overrides=runtime_economic_source_overrides,
        build_effective_settings=_build_effective_settings,
        resolve_layer_proxy_settings=_resolve_layer_proxy_settings,
        resolve_economic_settings=_resolve_economic_settings,
    )
    settings = settings_resolution_application.settings
    layer_proxy_settings = settings_resolution_application.layer_proxy_settings
    economic_settings = settings_resolution_application.economic_settings

    if not settings.include_in_planning:
        skip_application = _apply_production_order_skip(
            article_id=request.article_id,
            generated_at=now,
            lead_time_days_total=settings.lead_time_days_total,
            explainability_mode=request.explainability_mode,
            apply_production_order_explainability_mode=(
                _apply_production_order_explainability_mode
            ),
            apply_explainability_mode=_apply_explainability_mode,
            apply_production_order_response=_apply_production_order_response,
        )
        return skip_application.response

    economic_governance_application = _apply_production_order_economic_governance(
        article_id=request.article_id,
        economic_settings=economic_settings,
        overrides=request.overrides,
        capital_governance_mode_strict=CAPITAL_GOVERNANCE_MODE_STRICT,
        capital_governance_mode_safe_default=CAPITAL_GOVERNANCE_MODE_SAFE_DEFAULT,
        capital_governance_source_safe_default=CAPITAL_GOVERNANCE_SOURCE_SAFE_DEFAULT,
        build_available_capital_safe_default_warning=_build_available_capital_safe_default_warning,
        build_missing_available_capital_strict_detail=_build_missing_available_capital_strict_detail,
        resolve_economic_trust_and_capital_governance=(
            _resolve_economic_trust_and_capital_governance
        ),
    )
    economic_settings = economic_governance_application.economic_settings
    economics_trust = economic_governance_application.economics_trust
    economics_warnings = economic_governance_application.economics_warnings
    capital_governance = economic_governance_application.capital_governance

    prepared_inputs = _prepare_production_order_inputs(
        db=db,
        request=request,
        lead_time_days_total=settings.lead_time_days_total,
        load_admin_size_weights=_load_admin_size_weights,
        load_admin_in_flight_defaults=_load_admin_in_flight_defaults,
        normalize_weights=_normalize_weights,
        estimate_effective_in_flight_qty=_estimate_effective_in_flight_qty,
        load_wb_bundle_stock=_load_wb_bundle_stock,
        build_direct_missing_bundle_recipe_detail=_build_direct_missing_bundle_recipe_detail,
        build_direct_missing_sku_scope_detail=_build_direct_missing_sku_scope_detail,
    )
    bundle_type_ids = prepared_inputs.bundle_type_ids
    recipe_colors_by_bundle = prepared_inputs.recipe_colors_by_bundle
    all_recipe_color_ids = prepared_inputs.all_recipe_color_ids
    sku_by_color_size = prepared_inputs.sku_by_color_size
    color_to_sizes = prepared_inputs.color_to_sizes
    size_ids = prepared_inputs.size_ids
    size_weights_source = prepared_inputs.size_weights_source
    size_weights = prepared_inputs.size_weights
    stock_by_color_size = prepared_inputs.stock_by_color_size
    current_stock_by_color_size = prepared_inputs.current_stock_by_color_size
    in_flight_source = prepared_inputs.in_flight_source
    in_flight_raw_qty_total = prepared_inputs.in_flight_raw_qty_total
    in_flight_effective_qty_total = prepared_inputs.in_flight_effective_qty_total
    in_flight_effective_lines = prepared_inputs.in_flight_effective_lines
    in_flight_effective_by_color_size = prepared_inputs.in_flight_effective_by_color_size
    in_flight_eta_days_by_color_size = prepared_inputs.in_flight_eta_days_by_color_size
    demand_by_bundle = prepared_inputs.demand_by_bundle
    total_daily_sales = prepared_inputs.total_daily_sales
    bundle_stock_source = prepared_inputs.bundle_stock_source
    ready_bundle_stock_total = prepared_inputs.ready_bundle_stock_total
    shares_by_bundle = prepared_inputs.shares_by_bundle

    resource_allocation_application = _apply_production_order_resource_allocation(
        bundle_type_ids=bundle_type_ids,
        recipe_colors_by_bundle=recipe_colors_by_bundle,
        all_recipe_color_ids=all_recipe_color_ids,
        size_ids=size_ids,
        stock_by_color_size=stock_by_color_size,
        shares_by_bundle=shares_by_bundle,
        ready_bundle_stock_total=ready_bundle_stock_total,
        build_competition_aware_resource_allocation=(
            _build_competition_aware_resource_allocation
        ),
    )
    resource_allocation = resource_allocation_application.resource_allocation
    competition_raw_by_bundle = resource_allocation_application.competition_raw_by_bundle
    competition_raw_bundle_stock = resource_allocation_application.competition_raw_bundle_stock
    competition_raw_breakdown = resource_allocation_application.competition_raw_breakdown
    available_bundles_for_cover = resource_allocation_application.available_bundles_for_cover
    reorder_point_days = settings.lead_time_days_total + settings.safety_stock_days

    assorti_application = _apply_production_order_assorti_classification(
        db=db,
        article_settings=article_settings,
        global_settings=global_settings,
        bundle_type_ids=bundle_type_ids,
        parse_assorti_bundle_type_ids=_parse_assorti_bundle_type_ids,
        load_assorti_bundle_type_flags=_load_assorti_bundle_type_flags,
    )
    admin_assorti_bundle_type_ids = assorti_application.admin_assorti_bundle_type_ids
    global_assorti_bundle_type_ids = assorti_application.global_assorti_bundle_type_ids
    assorti_by_bundle_type = assorti_application.assorti_by_bundle_type
    assorti_classification_by_bundle_type = (
        assorti_application.assorti_classification_by_bundle_type
    )
    assorti_bundle_type_count = assorti_application.assorti_bundle_type_count
    main_bundle_type_count = assorti_application.main_bundle_type_count
    assorti_classification_source_breakdown = (
        assorti_application.assorti_classification_source_breakdown
    )

    layer1_stock_health_metrics = _build_layer1_stock_health_metrics(
        bundle_type_ids=bundle_type_ids,
        assorti_by_bundle_type=assorti_by_bundle_type,
        demand_by_bundle=demand_by_bundle,
        recipe_colors_by_bundle=recipe_colors_by_bundle,
        color_to_sizes=color_to_sizes,
        size_weights=size_weights,
        current_stock_by_color_size=stock_by_color_size,
        in_flight_effective_by_color_size=in_flight_effective_by_color_size,
        in_flight_eta_days_by_color_size=in_flight_eta_days_by_color_size,
        reorder_point_days=reorder_point_days,
        target_coverage_days=settings.target_coverage_days,
        margin_main_per_unit=economic_settings.margin_main_per_unit,
        margin_assorti_per_unit=economic_settings.margin_assorti_per_unit,
        unit_capital_per_unit=economic_settings.unit_capital_per_unit,
    )
    layer2_allocation_application = _apply_production_order_layer2_allocation(
        layer1_stock_health_metrics=layer1_stock_health_metrics,
        lead_time_days_total=settings.lead_time_days_total,
        margin_main_per_unit=economic_settings.margin_main_per_unit,
        margin_assorti_per_unit=economic_settings.margin_assorti_per_unit,
        unit_capital_per_unit=economic_settings.unit_capital_per_unit,
        capital_cost_rate=layer_proxy_settings.layer2_capital_cost_rate,
        stockout_penalty_weight=layer_proxy_settings.layer2_stockout_penalty_weight,
        overstock_penalty_weight=layer_proxy_settings.layer2_overstock_penalty_weight,
        build_layer2_allocation_decisions=_build_layer2_allocation_decisions,
    )
    layer2_allocation_decisions = layer2_allocation_application.layer2_allocation_decisions
    layer2_allocation_summary = layer2_allocation_application.layer2_allocation_summary
    layer2_summary_application = _apply_production_order_layer2_summary(
        layer2_allocation_decisions=layer2_allocation_decisions,
        layer2_allocation_summary=layer2_allocation_summary,
        build_layer2_contract_summary=_build_layer2_contract_summary,
        build_layer2_decision_quality_summary=_build_layer2_decision_quality_summary,
    )
    layer2_contract = layer2_summary_application.layer2_contract
    layer2_decision_quality = layer2_summary_application.layer2_decision_quality
    layer1_summary_application = _apply_production_order_layer1_summary(
        layer1_stock_health_metrics=layer1_stock_health_metrics,
        layer1_high_stockout_risk_threshold=LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD,
        build_layer1_contract_summary=_build_layer1_contract_summary,
    )
    layer1_avg_coverage_days = layer1_summary_application.layer1_avg_coverage_days
    layer1_high_stockout_risk_count = (
        layer1_summary_application.layer1_high_stockout_risk_count
    )
    layer1_contract = layer1_summary_application.layer1_contract

    risk_application = _apply_production_order_risk_level(
        total_daily_sales=total_daily_sales,
        available_bundles_for_cover=available_bundles_for_cover,
        reorder_point_days=reorder_point_days,
        alert_threshold_days=settings.alert_threshold_days,
        target_coverage_days=settings.target_coverage_days,
    )
    days_of_cover_estimate = risk_application.days_of_cover_estimate
    risk_level = risk_application.risk_level

    horizon_application = _apply_production_order_horizon(
        risk_level=risk_level,
        allow_order_with_buffer=settings.allow_order_with_buffer,
        total_daily_sales=total_daily_sales,
        lead_time_days_total=settings.lead_time_days_total,
        days_of_cover_estimate=days_of_cover_estimate,
        target_coverage_days=settings.target_coverage_days,
        safety_stock_days=settings.safety_stock_days,
        available_bundles_for_cover=available_bundles_for_cover,
        compute_economic_buffer_days=_compute_economic_buffer_days,
        ceil_to_int=_ceil_to_int,
    )
    economic_buffer_days = horizon_application.economic_buffer_days
    target_bundle_horizon_days = horizon_application.target_bundle_horizon_days
    required_bundle_units = horizon_application.required_bundle_units
    bundle_deficit_total = horizon_application.bundle_deficit_total

    line_requirements_application = _apply_production_order_line_requirements(
        bundle_deficit_total=bundle_deficit_total,
        bundle_type_ids=bundle_type_ids,
        all_recipe_color_ids=all_recipe_color_ids,
        recipe_colors_by_bundle=recipe_colors_by_bundle,
        shares_by_bundle=shares_by_bundle,
        color_to_sizes=color_to_sizes,
        size_weights=size_weights,
        stock_by_color_size=stock_by_color_size,
        build_line_requirements_plan=_build_line_requirements_plan,
    )
    color_probability = line_requirements_application.color_probability
    line_required = line_requirements_application.line_required
    line_qty = line_requirements_application.line_qty

    layer3_application = _apply_production_order_layer3(
        line_qty=line_qty,
        layer2_allocation_decisions=layer2_allocation_decisions,
        layer1_stock_health_metrics=layer1_stock_health_metrics,
        layer3_stockout_boost_max=layer_proxy_settings.layer3_stockout_boost_max,
        layer3_overstock_dampen_max=layer_proxy_settings.layer3_overstock_dampen_max,
        apply_layer3_purchase_shaping=_apply_layer3_purchase_shaping,
        build_layer3_contract_summary=_build_layer3_contract_summary,
    )
    layer3_decision_by_line = layer3_application.layer3_decision_by_line
    layer3_purchase_shaping = layer3_application.layer3_purchase_shaping
    layer3_contract = layer3_application.layer3_contract

    constraint_application = _apply_production_order_constraints(
        db=db,
        article_id=request.article_id,
        resource_allocation=resource_allocation,
        all_recipe_color_ids=all_recipe_color_ids,
        target_horizon_days=target_bundle_horizon_days,
        shared_color_pool_observation_window_days=shared_color_pool_observation_window_days,
        shared_color_pool_as_of_date=shared_color_pool_as_of_date,
        fabric_min_batch_default=settings.fabric_min_batch_default,
        elastic_min_batch_default=settings.elastic_min_batch_default,
        line_qty=line_qty,
        color_to_sizes=color_to_sizes,
        size_weights=size_weights,
        sku_by_color_size=sku_by_color_size,
        apply_shared_color_pool_fabric_min_batches=_apply_shared_color_pool_fabric_min_batches,
        apply_elastic_min_batch_uplift=_apply_elastic_min_batch_uplift,
    )
    constraints_applied = constraint_application.constraints_applied
    shared_color_pool = constraint_application.shared_color_pool
    applicable_elastic_type_ids = constraint_application.applicable_elastic_type_ids
    elastic_scope_line_keys = constraint_application.elastic_scope_line_keys
    elastic_scope_mode = constraint_application.elastic_scope_mode
    scoped_elastic_rows_count = constraint_application.scoped_elastic_rows_count
    elastic_uplift_delta = constraint_application.elastic_uplift_delta
    elastic_uplift_scope = constraint_application.elastic_uplift_scope
    elastic_uplift_keys = constraint_application.elastic_uplift_keys
    elastic_uplift_line_alloc = constraint_application.elastic_uplift_line_alloc

    candidate_lines_application = _apply_production_order_candidate_lines(
        article_id=request.article_id,
        line_qty=line_qty,
        layer3_decision_by_line=layer3_decision_by_line,
        build_candidate_lines=_build_candidate_lines,
    )
    candidate_lines = candidate_lines_application.candidate_lines

    capital_application = _apply_production_order_capital_constraints(
        candidate_lines=candidate_lines,
        layer3_decision_by_line=layer3_decision_by_line,
        layer1_stock_health_metrics=layer1_stock_health_metrics,
        margin_main_per_unit=economic_settings.margin_main_per_unit,
        margin_assorti_per_unit=economic_settings.margin_assorti_per_unit,
        unit_capital_per_unit=economic_settings.unit_capital_per_unit,
        available_capital=economic_settings.available_capital,
        capital_cost_rate=layer_proxy_settings.layer2_capital_cost_rate,
        stockout_penalty_weight=layer_proxy_settings.layer2_stockout_penalty_weight,
        overstock_penalty_weight=layer_proxy_settings.layer2_overstock_penalty_weight,
        build_line_objective_capital_rankings=_build_line_objective_capital_rankings,
        apply_capital_constraint_to_candidate_lines=_apply_capital_constraint_to_candidate_lines,
        build_capital_constraint_contract_summary=_build_capital_constraint_contract_summary,
    )
    capital_unpack_application = _apply_production_order_capital_unpack(
        capital_application=capital_application,
    )
    candidate_lines = capital_unpack_application.candidate_lines
    capital_rankings = capital_unpack_application.capital_rankings
    capital_constraint_summary = capital_unpack_application.capital_constraint_summary
    capital_constraint_contract = capital_unpack_application.capital_constraint_contract
    candidate_total_units = capital_unpack_application.candidate_total_units

    layer4_application = _apply_production_order_layer4_analysis(
        candidate_total_units=candidate_total_units,
        planning_horizon_days=request.planning_horizon_days,
        available_bundles_for_cover=available_bundles_for_cover,
        total_daily_sales=total_daily_sales,
        reorder_point_days=reorder_point_days,
        layer3_purchase_shaping=layer3_purchase_shaping,
        available_capital=economic_settings.available_capital,
        unit_capital_per_unit=economic_settings.unit_capital_per_unit,
        margin_main_per_unit=economic_settings.margin_main_per_unit,
        margin_assorti_per_unit=economic_settings.margin_assorti_per_unit,
        average_realized_price_main=economic_settings.average_realized_price_main,
        average_realized_price_assorti=economic_settings.average_realized_price_assorti,
        capital_cost_rate=layer_proxy_settings.layer2_capital_cost_rate,
        stockout_penalty_weight=layer_proxy_settings.layer2_stockout_penalty_weight,
        overstock_penalty_weight=layer_proxy_settings.layer2_overstock_penalty_weight,
        build_layer4_scenarios=_build_layer4_scenarios,
        build_capital_gap_summary=_build_capital_gap_summary,
        build_layer4_contract_summary=_build_layer4_contract_summary,
        build_layer4_aggregate_deltas=_build_layer4_aggregate_deltas,
    )
    layer4_unpack_application = _apply_production_order_layer4_unpack(
        layer4_application=layer4_application,
    )
    expected_horizon_sales = layer4_unpack_application.expected_horizon_sales
    layer4_scenarios = layer4_unpack_application.layer4_scenarios
    capital_gap_summary = layer4_unpack_application.capital_gap_summary
    layer4_contract = layer4_unpack_application.layer4_contract
    layer4_aggregate_deltas = layer4_unpack_application.layer4_aggregate_deltas

    layer5_application = _apply_production_order_layer5_analysis(
        risk_level=risk_level,
        layer4_scenarios=layer4_scenarios,
        in_flight_effective_qty_total=in_flight_effective_qty_total,
        unavoidable_stockout_risk_threshold=layer_proxy_settings.layer5_unavoidable_stockout_risk_threshold,
        accelerate_production_risk_threshold=layer_proxy_settings.layer5_accelerate_production_risk_threshold,
        accelerate_action_cost_rate=layer_proxy_settings.layer5_accelerate_action_cost_rate,
        price_slowdown_lost_volume_rate=layer_proxy_settings.layer5_price_slowdown_lost_volume_rate,
        reduce_order_marginal_profit_rate=layer_proxy_settings.layer5_reduce_order_marginal_profit_rate,
        build_layer5_intervention_signals=_build_layer5_intervention_signals,
        build_layer5_contract_summary=_build_layer5_contract_summary,
    )
    layer5_unpack_application = _apply_production_order_layer5_unpack(
        layer5_application=layer5_application,
    )
    layer5_intervention = layer5_unpack_application.layer5_intervention
    layer5_contract = layer5_unpack_application.layer5_contract
    layer5_intervention_meta = layer5_unpack_application.layer5_intervention_meta

    scope_recommendation = _apply_production_order_scope_and_recommendation(
        bundle_stock_source=bundle_stock_source,
        in_flight_source=in_flight_source,
        size_weights_source=size_weights_source,
        bundle_type_ids=bundle_type_ids,
        recipe_colors_by_bundle=recipe_colors_by_bundle,
        all_recipe_color_ids=all_recipe_color_ids,
        size_ids=size_ids,
        current_stock_by_color_size=current_stock_by_color_size,
        in_flight_effective_by_color_size=in_flight_effective_by_color_size,
        shares_by_bundle=shares_by_bundle,
        ready_bundle_stock_total=ready_bundle_stock_total,
        total_daily_sales=total_daily_sales,
        risk_level=risk_level,
        candidate_total_units=candidate_total_units,
        allow_order_with_buffer=settings.allow_order_with_buffer,
        priority=settings.priority,
        now=now,
        candidate_lines=candidate_lines,
        lead_time_days_total=settings.lead_time_days_total,
        estimate_raw_bundle_stock=_estimate_competition_aware_raw_bundle_stock,
        build_physical_scope_and_arrival_projection=build_physical_scope_and_arrival_projection,
        build_recommendation_and_alternatives=_build_recommendation_and_alternatives,
    )
    scope_recommendation_unpack = _apply_production_order_scope_recommendation_unpack(
        scope_recommendation=scope_recommendation,
    )
    physical_scope = scope_recommendation_unpack.physical_scope
    arrival_projection = scope_recommendation_unpack.arrival_projection
    action = scope_recommendation_unpack.action
    recommendation = scope_recommendation_unpack.recommendation
    alternatives = scope_recommendation_unpack.alternatives

    explanation_warning_application = _apply_production_order_explanation_warnings(
        economics_warnings=economics_warnings,
        article_id=request.article_id,
        invalid_values_ignored=layer_proxy_settings.invalid_values_ignored,
        threshold_order_adjusted=layer_proxy_settings.threshold_order_adjusted,
        accelerate_threshold_effective=layer_proxy_settings.layer5_accelerate_production_risk_threshold,
        unavoidable_threshold_effective=layer_proxy_settings.layer5_unavoidable_stockout_risk_threshold,
        threshold_effective_source=layer_proxy_settings.source.get(
            "layer5_accelerate_production_risk_threshold"
        ),
        arrival_projection_status=arrival_projection.status,
        action=action,
        capital_constraint_summary=capital_constraint_summary,
        projected_shortage_before_arrival=arrival_projection.projected_shortage_before_arrival,
        available_capital_effective=economic_settings.available_capital,
        build_explanation_warnings=_build_explanation_warnings,
        build_layer_proxy_invalid_values_ignored_warning=_build_layer_proxy_invalid_values_ignored_warning,
        build_layer5_threshold_clamped_warning=_build_layer5_threshold_clamped_warning,
        build_shortage_wait_blocked_by_capital_constraint_warning=(
            _build_shortage_wait_blocked_by_capital_constraint_warning
        ),
    )
    explanation_warning_unpack = _apply_production_order_explanation_warning_unpack(
        explanation_warning_application=explanation_warning_application,
    )
    explanation_warnings = explanation_warning_unpack.explanation_warnings

    alpha_proxy_application = _apply_production_order_alpha_proxy_economics(
        layer4_scenario_factors=LAYER4_SCENARIO_FACTORS,
        layer_proxy_value_source=LAYER_PROXY_VALUE_SOURCE,
        economics_formula_version=ECONOMICS_FORMULA_VERSION,
        economic_calibration_state=economic_settings.calibration_state,
        economics_trust=economics_trust,
        capital_governance=capital_governance,
        layer1_high_stockout_risk_threshold=LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD,
        layer2_allocation_method=LAYER2_ALLOCATION_METHOD_CANONICAL,
        layer2_allocation_method_canonical=LAYER2_ALLOCATION_METHOD_CANONICAL,
        layer2_legacy_allocation_method=LAYER2_ALLOCATION_METHOD,
        layer2_decision_gate=LAYER2_DECISION_GATE_CANONICAL,
        layer2_decision_gate_canonical=LAYER2_DECISION_GATE_CANONICAL,
        layer2_legacy_decision_gate=LAYER2_DECISION_GATE_LEGACY,
        layer2_near_tie_objective_gap_threshold=LAYER2_NEAR_TIE_OBJECTIVE_GAP_THRESHOLD,
        layer2_near_tie_profit_gap_threshold=LAYER2_NEAR_TIE_OBJECTIVE_GAP_THRESHOLD,
        layer2_objective_parameters={
            "capital_cost_rate": layer_proxy_settings.layer2_capital_cost_rate,
            "stockout_penalty_weight": layer_proxy_settings.layer2_stockout_penalty_weight,
            "overstock_penalty_weight": layer_proxy_settings.layer2_overstock_penalty_weight,
        },
        main_margin_proxy=economic_settings.margin_main_per_unit,
        assorti_margin_proxy=economic_settings.margin_assorti_per_unit,
        unit_capital_proxy=economic_settings.unit_capital_per_unit,
        economic_inputs={
            "production_cost_per_unit": economic_settings.production_cost_per_unit,
            "logistics_cost_per_unit": economic_settings.logistics_cost_per_unit,
            "wb_commission_percent_main": economic_settings.wb_commission_percent_main,
            "wb_commission_percent_assorti": economic_settings.wb_commission_percent_assorti,
            "average_realized_price_main": economic_settings.average_realized_price_main,
            "average_realized_price_assorti": economic_settings.average_realized_price_assorti,
            "available_capital": economic_settings.available_capital,
        },
        economic_source=economic_settings.source,
        layer3_purchase_factors=LAYER3_PURCHASE_FACTOR_BY_DECISION,
        layer3_calibration_method=LAYER3_CALIBRATION_METHOD,
        layer3_stockout_boost_max=layer_proxy_settings.layer3_stockout_boost_max,
        layer3_overstock_dampen_max=layer_proxy_settings.layer3_overstock_dampen_max,
        layer3_stockout_weight_by_decision=LAYER3_STOCKOUT_WEIGHT_BY_DECISION,
        layer3_overstock_weight_by_decision=LAYER3_OVERSTOCK_WEIGHT_BY_DECISION,
        layer3_factor_bounds=LAYER3_FACTOR_BOUNDS,
        layer_proxy_source=layer_proxy_settings.source,
        layer5_threshold_order_adjusted=layer_proxy_settings.threshold_order_adjusted,
        layer4_contract_version=LAYER4_CONTRACT_VERSION,
        layer5_unavoidable_stockout_risk_threshold=layer_proxy_settings.layer5_unavoidable_stockout_risk_threshold,
        layer5_accelerate_production_risk_threshold=layer_proxy_settings.layer5_accelerate_production_risk_threshold,
        layer5_accelerate_action_cost_rate=layer_proxy_settings.layer5_accelerate_action_cost_rate,
        layer5_price_slowdown_lost_volume_rate=layer_proxy_settings.layer5_price_slowdown_lost_volume_rate,
        layer5_reduce_order_marginal_profit_rate=layer_proxy_settings.layer5_reduce_order_marginal_profit_rate,
        build_layer2_legacy_alias_deprecation_plan=_build_layer2_legacy_alias_deprecation_plan,
        build_alpha_proxy_economics_meta=_build_alpha_proxy_economics_meta,
    )
    alpha_proxy_unpack = _apply_production_order_alpha_proxy_unpack(
        alpha_proxy_application=alpha_proxy_application,
    )
    layer4_scenario_factor_items = alpha_proxy_unpack.layer4_scenario_factor_items
    alpha_proxy_economics = alpha_proxy_unpack.alpha_proxy_economics

    explanation_application = _apply_production_order_explanation(
        risk_level=risk_level,
        days_of_cover_estimate=days_of_cover_estimate,
        reorder_point_days=reorder_point_days,
        lead_time_days_total=settings.lead_time_days_total,
        safety_stock_days=settings.safety_stock_days,
        total_daily_sales=total_daily_sales,
        planning_horizon_days=request.planning_horizon_days,
        expected_horizon_sales=expected_horizon_sales,
        ready_bundle_stock_total=ready_bundle_stock_total,
        competition_raw_bundle_stock=competition_raw_bundle_stock,
        competition_raw_breakdown=competition_raw_breakdown,
        physical_scope=physical_scope,
        resource_allocation=resource_allocation,
        arrival_projection=arrival_projection,
        shared_color_pool=shared_color_pool,
        required_bundle_units=required_bundle_units,
        available_bundles_for_cover=available_bundles_for_cover,
        bundle_deficit_total=bundle_deficit_total,
        allow_order_with_buffer=settings.allow_order_with_buffer,
        economic_buffer_days=economic_buffer_days,
        target_bundle_horizon_days=target_bundle_horizon_days,
        size_weights_source=size_weights_source,
        in_flight_source=in_flight_source,
        bundle_stock_source=bundle_stock_source,
        economics_trust=economics_trust,
        capital_governance=capital_governance,
        explanation_warnings=explanation_warnings,
        assorti_classification_source=ASSORTI_CLASSIFICATION_SOURCE,
        admin_assorti_bundle_type_ids=admin_assorti_bundle_type_ids,
        global_assorti_bundle_type_ids=global_assorti_bundle_type_ids,
        assorti_bundle_type_count=assorti_bundle_type_count,
        main_bundle_type_count=main_bundle_type_count,
        assorti_classification_source_breakdown=assorti_classification_source_breakdown,
        assorti_classification_by_bundle_type=assorti_classification_by_bundle_type,
        layer1_stock_health_metrics=layer1_stock_health_metrics,
        layer1_avg_coverage_days=layer1_avg_coverage_days,
        layer1_high_stockout_risk_count=layer1_high_stockout_risk_count,
        layer1_high_stockout_risk_threshold=LAYER1_HIGH_STOCKOUT_RISK_THRESHOLD,
        layer1_contract=layer1_contract,
        layer2_allocation_method=LAYER2_ALLOCATION_METHOD_CANONICAL,
        layer2_allocation_method_canonical=LAYER2_ALLOCATION_METHOD_CANONICAL,
        layer2_legacy_allocation_method=LAYER2_ALLOCATION_METHOD,
        layer2_allocation_decisions=layer2_allocation_decisions,
        layer2_allocation_summary=layer2_allocation_summary,
        layer2_contract=layer2_contract,
        layer2_decision_quality=layer2_decision_quality,
        layer2_decision_gate=LAYER2_DECISION_GATE_CANONICAL,
        layer2_decision_gate_canonical=LAYER2_DECISION_GATE_CANONICAL,
        layer2_legacy_decision_gate=LAYER2_DECISION_GATE_LEGACY,
        layer2_objective_parameters={
            "capital_cost_rate": layer_proxy_settings.layer2_capital_cost_rate,
            "stockout_penalty_weight": layer_proxy_settings.layer2_stockout_penalty_weight,
            "overstock_penalty_weight": layer_proxy_settings.layer2_overstock_penalty_weight,
        },
        layer2_objective_source={
            "capital_cost_rate": layer_proxy_settings.source.get("layer2_capital_cost_rate"),
            "stockout_penalty_weight": layer_proxy_settings.source.get(
                "layer2_stockout_penalty_weight"
            ),
            "overstock_penalty_weight": layer_proxy_settings.source.get(
                "layer2_overstock_penalty_weight"
            ),
        },
        layer3_purchase_factors=LAYER3_PURCHASE_FACTOR_BY_DECISION,
        layer3_contract=layer3_contract,
        layer3_purchase_shaping=layer3_purchase_shaping,
        layer4_scenario_factor_items=layer4_scenario_factor_items,
        layer4_contract=layer4_contract,
        layer4_aggregate_deltas=layer4_aggregate_deltas,
        layer4_scenarios=layer4_scenarios,
        layer5_intervention=layer5_intervention,
        layer5_contract=layer5_contract,
        layer5_intervention_meta=layer5_intervention_meta,
        capital_gap_summary=capital_gap_summary,
        capital_constraint_summary=capital_constraint_summary,
        capital_constraint_contract=capital_constraint_contract,
        alpha_proxy_economics=alpha_proxy_economics,
        in_flight_raw_qty_total=in_flight_raw_qty_total,
        in_flight_effective_qty_total=in_flight_effective_qty_total,
        in_flight_effective_lines=in_flight_effective_lines,
        elastic_scope_mode=elastic_scope_mode,
        applicable_elastic_type_ids=applicable_elastic_type_ids,
        scoped_elastic_rows_count=scoped_elastic_rows_count,
        elastic_scope_line_count=len(elastic_scope_line_keys),
        elastic_uplift_delta=elastic_uplift_delta,
        elastic_uplift_scope=elastic_uplift_scope,
        elastic_uplift_keys=elastic_uplift_keys,
        elastic_uplift_line_alloc=elastic_uplift_line_alloc,
        fabric_constraint_count=len(constraints_applied.fabric_min_batches),
        elastic_constraint_count=len(constraints_applied.elastic_min_batches),
        assorti_classification_admin_fallback_source=(
            ASSORTI_CLASSIFICATION_ADMIN_FALLBACK_SOURCE
        ),
        assorti_classification_global_fallback_source=(
            ASSORTI_CLASSIFICATION_GLOBAL_FALLBACK_SOURCE
        ),
        main_margin_proxy=economic_settings.margin_main_per_unit,
        assorti_margin_proxy=economic_settings.margin_assorti_per_unit,
        unit_capital_proxy=economic_settings.unit_capital_per_unit,
        economic_buffer_enabled=settings.allow_order_with_buffer,
        build_layer2_legacy_alias_deprecation_plan=_build_layer2_legacy_alias_deprecation_plan,
        build_explanation_steps=_build_explanation_steps,
        build_explanation_meta=_build_explanation_meta,
    )
    explanation_unpack = _apply_production_order_explanation_unpack(
        explanation_application=explanation_application,
    )
    explanation = explanation_unpack.explanation

    explainability_mode_application = _apply_production_order_explainability_mode(
        explanation=explanation,
        mode=request.explainability_mode,
        apply_explainability_mode=_apply_explainability_mode,
    )
    explainability_mode_unpack = _apply_production_order_explainability_mode_unpack(
        explainability_mode_application=explainability_mode_application,
    )
    explanation = explainability_mode_unpack.explanation

    response_application = _apply_production_order_response(
        status="ok",
        article_id=request.article_id,
        generated_at=now,
        risk_level=risk_level,
        days_of_cover_estimate=float(days_of_cover_estimate),
        lead_time_days_total=settings.lead_time_days_total,
        recommendation=recommendation,
        constraints_applied=constraints_applied,
        physical_scope=physical_scope,
        arrival_projection=arrival_projection,
        alternatives=alternatives,
        explanation=explanation,
    )
    return response_application.response
