from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from app.schemas.planning_production_order import ProductionOrderExplanationBlock


@dataclass(frozen=True)
class _ExplanationApplicationResult:
    explanation: ProductionOrderExplanationBlock


def _apply_production_order_explanation(
    *,
    risk_level: str,
    days_of_cover_estimate: float,
    reorder_point_days: int,
    lead_time_days_total: int,
    safety_stock_days: int,
    total_daily_sales: float,
    planning_horizon_days: int,
    expected_horizon_sales: float,
    ready_bundle_stock_total: int,
    competition_raw_bundle_stock: int,
    competition_raw_breakdown: str,
    physical_scope: object,
    resource_allocation: object,
    arrival_projection: object,
    shared_color_pool: dict[str, object],
    required_bundle_units: int,
    available_bundles_for_cover: int,
    bundle_deficit_total: int,
    allow_order_with_buffer: bool,
    economic_buffer_days: int,
    target_bundle_horizon_days: int,
    size_weights_source: str,
    in_flight_source: str,
    bundle_stock_source: str,
    economics_trust: dict[str, object],
    capital_governance: dict[str, object],
    explanation_warnings: list[dict[str, object]],
    assorti_classification_source: str,
    admin_assorti_bundle_type_ids: list[int],
    global_assorti_bundle_type_ids: list[int],
    assorti_bundle_type_count: int,
    main_bundle_type_count: int,
    assorti_classification_source_breakdown: dict[str, int],
    assorti_classification_by_bundle_type: dict[str, object],
    layer1_stock_health_metrics: list[dict[str, object]],
    layer1_avg_coverage_days: float,
    layer1_high_stockout_risk_count: int,
    layer1_high_stockout_risk_threshold: float,
    layer1_contract: dict[str, object],
    layer2_allocation_method: str,
    layer2_allocation_method_canonical: str,
    layer2_legacy_allocation_method: str,
    layer2_allocation_decisions: list[dict[str, object]],
    layer2_allocation_summary: dict[str, object],
    layer2_contract: dict[str, object],
    layer2_decision_quality: dict[str, object],
    layer2_decision_gate: str,
    layer2_decision_gate_canonical: str,
    layer2_legacy_decision_gate: str,
    layer2_objective_parameters: dict[str, object],
    layer2_objective_source: dict[str, object],
    layer3_purchase_factors: dict[str, object],
    layer3_contract: dict[str, object],
    layer3_purchase_shaping: dict[str, object],
    layer4_scenario_factor_items: list[dict[str, object]],
    layer4_contract: dict[str, object],
    layer4_aggregate_deltas: dict[str, object],
    layer4_scenarios: list[dict[str, object]],
    layer5_intervention: dict[str, object],
    layer5_contract: dict[str, object],
    layer5_intervention_meta: dict[str, object],
    capital_gap_summary: dict[str, object],
    capital_constraint_summary: dict[str, object],
    capital_constraint_contract: dict[str, object],
    alpha_proxy_economics: dict[str, object],
    in_flight_raw_qty_total: int,
    in_flight_effective_qty_total: int,
    in_flight_effective_lines: int,
    elastic_scope_mode: str,
    applicable_elastic_type_ids: list[int],
    scoped_elastic_rows_count: int,
    elastic_scope_line_count: int,
    elastic_uplift_delta: int,
    elastic_uplift_scope: str,
    elastic_uplift_keys: list[tuple[int, int]],
    elastic_uplift_line_alloc: dict[tuple[int, int], int],
    fabric_constraint_count: int,
    elastic_constraint_count: int,
    assorti_classification_admin_fallback_source: str,
    assorti_classification_global_fallback_source: str,
    main_margin_proxy: float,
    assorti_margin_proxy: float,
    unit_capital_proxy: float,
    economic_buffer_enabled: bool,
    build_layer2_legacy_alias_deprecation_plan: Callable[[], dict[str, object]],
    build_explanation_steps: Callable[..., list[str]],
    build_explanation_meta: Callable[..., dict[str, object]],
) -> _ExplanationApplicationResult:
    explanation = ProductionOrderExplanationBlock(
        summary=(
            f"Риск {risk_level}: оценка покрытия {days_of_cover_estimate:.1f} дней при reorder point "
            f"{reorder_point_days} дней (lead_time={lead_time_days_total}, "
            f"safety_stock={safety_stock_days})."
        ),
        steps=build_explanation_steps(
            total_daily_sales=total_daily_sales,
            planning_horizon_days=planning_horizon_days,
            expected_horizon_sales=expected_horizon_sales,
            ready_bundle_stock_total=ready_bundle_stock_total,
            competition_raw_bundle_stock=competition_raw_bundle_stock,
            competition_raw_breakdown=competition_raw_breakdown,
            physical_scope=physical_scope,
            resource_allocation=resource_allocation,
            arrival_projection=arrival_projection,
            shared_color_pool=shared_color_pool,
            required_bundle_units=required_bundle_units,
            available_bundles_for_cover=available_bundles_for_cover,
            bundle_deficit_total=bundle_deficit_total,
            lead_time_days_total=lead_time_days_total,
            safety_stock_days=safety_stock_days,
            reorder_point_days=reorder_point_days,
            allow_order_with_buffer=allow_order_with_buffer,
            economic_buffer_days=economic_buffer_days,
            target_bundle_horizon_days=target_bundle_horizon_days,
            size_weights_source=size_weights_source,
            in_flight_source=in_flight_source,
            bundle_stock_source=bundle_stock_source,
            economics_trust=economics_trust,
            explanation_warnings=explanation_warnings,
            assorti_classification_source=assorti_classification_source,
            admin_assorti_bundle_type_ids=sorted(admin_assorti_bundle_type_ids),
            global_assorti_bundle_type_ids=sorted(global_assorti_bundle_type_ids),
            assorti_bundle_type_count=assorti_bundle_type_count,
            main_bundle_type_count=main_bundle_type_count,
            assorti_classification_source_breakdown=assorti_classification_source_breakdown,
            layer1_sku_count=len(layer1_stock_health_metrics),
            layer1_avg_coverage_days=layer1_avg_coverage_days,
            layer1_high_stockout_risk_count=layer1_high_stockout_risk_count,
            layer1_high_stockout_risk_threshold=layer1_high_stockout_risk_threshold,
            layer1_contract_status=layer1_contract["status"],
            layer2_allocation_method_canonical=layer2_allocation_method_canonical,
            layer2_allocation_method_legacy=layer2_legacy_allocation_method,
            layer2_decision_gate_canonical=layer2_decision_gate_canonical,
            layer2_decision_gate_legacy=layer2_legacy_decision_gate,
            layer2_allocation_summary=layer2_allocation_summary,
            layer2_decision_quality=layer2_decision_quality,
            layer2_contract_status=layer2_contract["status"],
            layer3_purchase_shaping=layer3_purchase_shaping,
            layer3_contract_status=layer3_contract["status"],
            layer4_scenarios=layer4_scenarios,
            layer4_contract=layer4_contract,
            layer4_aggregate_deltas=layer4_aggregate_deltas,
            capital_gap_summary=capital_gap_summary,
            capital_constraint_summary=capital_constraint_summary,
            capital_constraint_contract_status=capital_constraint_contract["status"],
            layer5_intervention=layer5_intervention,
            layer5_contract_status=layer5_contract["status"],
            elastic_scope_mode=elastic_scope_mode,
            applicable_elastic_type_ids=sorted(applicable_elastic_type_ids),
            scoped_elastic_rows_count=scoped_elastic_rows_count,
            elastic_scope_line_count=elastic_scope_line_count,
            elastic_uplift_delta=elastic_uplift_delta,
            elastic_uplift_scope=elastic_uplift_scope,
            elastic_uplift_keys=elastic_uplift_keys,
            elastic_uplift_line_alloc=elastic_uplift_line_alloc,
            in_flight_raw_qty_total=in_flight_raw_qty_total,
            in_flight_effective_qty_total=in_flight_effective_qty_total,
            in_flight_effective_lines=in_flight_effective_lines,
            fabric_constraint_count=fabric_constraint_count,
            elastic_constraint_count=elastic_constraint_count,
        ),
        meta=build_explanation_meta(
            explanation_warnings=explanation_warnings,
            economics_trust=economics_trust,
            capital_governance=capital_governance,
            size_weights_source=size_weights_source,
            in_flight_source=in_flight_source,
            bundle_stock_source=bundle_stock_source,
            physical_scope=physical_scope,
            arrival_projection=arrival_projection,
            shared_color_pool=shared_color_pool,
            lead_time_days_total=lead_time_days_total,
            safety_stock_days=safety_stock_days,
            reorder_point_days=reorder_point_days,
            layer1_stock_health_metrics=layer1_stock_health_metrics,
            layer1_avg_coverage_days=layer1_avg_coverage_days,
            layer1_high_stockout_risk_count=layer1_high_stockout_risk_count,
            layer1_high_stockout_risk_threshold=layer1_high_stockout_risk_threshold,
            layer1_contract=layer1_contract,
            assorti_classification_source=assorti_classification_source,
            assorti_classification_admin_fallback_source=assorti_classification_admin_fallback_source,
            assorti_classification_global_fallback_source=assorti_classification_global_fallback_source,
            admin_assorti_bundle_type_ids=sorted(admin_assorti_bundle_type_ids),
            global_assorti_bundle_type_ids=sorted(global_assorti_bundle_type_ids),
            assorti_bundle_type_count=assorti_bundle_type_count,
            main_bundle_type_count=main_bundle_type_count,
            assorti_classification_source_breakdown=assorti_classification_source_breakdown,
            assorti_classification_by_bundle_type=assorti_classification_by_bundle_type,
            main_margin_proxy=main_margin_proxy,
            assorti_margin_proxy=assorti_margin_proxy,
            unit_capital_proxy=unit_capital_proxy,
            layer2_allocation_method=layer2_allocation_method,
            layer2_allocation_method_canonical=layer2_allocation_method_canonical,
            layer2_legacy_allocation_method=layer2_legacy_allocation_method,
            layer2_legacy_alias_deprecation_plan=build_layer2_legacy_alias_deprecation_plan(),
            layer2_allocation_decisions=layer2_allocation_decisions,
            layer2_allocation_summary=layer2_allocation_summary,
            layer2_contract=layer2_contract,
            layer2_decision_quality=layer2_decision_quality,
            layer2_decision_gate=layer2_decision_gate,
            layer2_decision_gate_canonical=layer2_decision_gate_canonical,
            layer2_legacy_decision_gate=layer2_legacy_decision_gate,
            layer2_objective_parameters=layer2_objective_parameters,
            layer2_objective_source=layer2_objective_source,
            layer3_purchase_factors=layer3_purchase_factors,
            layer3_contract=layer3_contract,
            layer3_purchase_shaping=layer3_purchase_shaping,
            layer4_scenario_factor_items=layer4_scenario_factor_items,
            layer4_contract=layer4_contract,
            layer4_aggregate_deltas=layer4_aggregate_deltas,
            layer4_scenarios=layer4_scenarios,
            layer5_intervention_meta=layer5_intervention_meta,
            capital_gap_summary=capital_gap_summary,
            capital_constraint_summary=capital_constraint_summary,
            resource_allocation=resource_allocation,
            alpha_proxy_economics=alpha_proxy_economics,
            economic_buffer_enabled=economic_buffer_enabled,
            economic_buffer_days=economic_buffer_days,
            target_bundle_horizon_days=target_bundle_horizon_days,
            in_flight_raw_qty_total=in_flight_raw_qty_total,
            in_flight_effective_qty_total=in_flight_effective_qty_total,
            in_flight_effective_lines=in_flight_effective_lines,
            elastic_scope_mode=elastic_scope_mode,
            applicable_elastic_type_ids=sorted(applicable_elastic_type_ids),
            scoped_elastic_rows_count=scoped_elastic_rows_count,
            elastic_scope_line_count=elastic_scope_line_count,
            elastic_uplift_delta=elastic_uplift_delta,
            elastic_uplift_scope=elastic_uplift_scope,
            elastic_uplift_keys=elastic_uplift_keys,
            elastic_uplift_line_alloc=elastic_uplift_line_alloc,
        ),
    )
    return _ExplanationApplicationResult(explanation=explanation)
